/* Textos de implantación genéricos por medida del Anexo II para los casos de ejemplo.
 * Marcadores: {ORG} organización · {SIEM} {IDP} {CLOUD} {BACKUP} {EDR} {ITSM} {CPD} {WAF} {MAIL} herramientas del caso.
 * Material docente ficticio: describe implantaciones plausibles, no reales. */
'use strict';
module.exports = {
  'org.1': { org: 'Política de Seguridad de la Información aprobada por el órgano de gobierno de {ORG}, publicada y revisada anualmente.', tec: 'Publicación en la intranet con acuse de lectura.', ev: 'PSI-01; acta de aprobación' },
  'org.2': { org: 'Normativas de uso aceptable, puesto de trabajo, contraseñas y clasificación de la información.', tec: 'Aceptación electrónica de normativas en el alta de usuarios.', ev: 'NOR-01..04; registro de aceptaciones' },
  'org.3': { org: 'Catálogo de procedimientos operativos de seguridad con responsable y versión.', tec: 'Gestor documental con flujo de aprobación.', ev: 'Índice de procedimientos PRO-xx' },
  'org.4': { org: 'Procedimiento de autorización previa para entrada en producción, equipos y comunicaciones.', tec: 'Flujo de aprobación en {ITSM}.', ev: 'PRO-AUT-01; tickets de autorización' },
  'op.pl.1': { org: 'Análisis de riesgos MAGERIT revisado anualmente y ante cambios significativos.', tec: 'Herramienta de análisis de riesgos con histórico de versiones.', ev: 'Informe de análisis de riesgos; acta del comité' },
  'op.pl.2': { org: 'Documento de arquitectura de seguridad: zonas, flujos, puntos de acceso y controles.', tec: 'Diagramas de red y de flujos mantenidos en el repositorio de arquitectura.', ev: 'ARQ-01; diagramas de red' },
  'op.pl.3': { org: 'Requisitos de seguridad en los pliegos y en las adquisiciones.', tec: 'Checklist de seguridad en compras integrado en {ITSM}.', ev: 'PRO-ADQ-01; pliegos tipo' },
  'op.pl.4': { org: 'Planificación anual de capacidad de almacenamiento, cómputo y comunicaciones.', tec: 'Monitorización de capacidad con umbrales y alertas.', ev: 'Informe de capacidad anual' },
  'op.pl.5': { org: 'Preferencia por productos del catálogo CPSTIC en funcionalidades de seguridad.', tec: 'Inventario de productos de seguridad con su cualificación.', ev: 'Inventario de productos de seguridad' },
  'op.acc.1': { org: 'Identificadores únicos y nominales; prohibición de cuentas compartidas.', tec: 'Directorio corporativo {IDP} con ciclo de vida de identidades.', ev: 'PRO-IAM-01; informe de cuentas' },
  'op.acc.2': { org: 'Matriz de perfiles y roles por aplicación según mínimo privilegio.', tec: 'Control de acceso basado en roles en {IDP} y aplicaciones.', ev: 'Matriz de roles; revisiones de acceso' },
  'op.acc.3': { org: 'Segregación entre desarrollo, operación y auditoría; tareas críticas con doble control.', tec: 'Perfiles separados en {IDP} y en las consolas de administración.', ev: 'Matriz de segregación' },
  'op.acc.4': { org: 'Altas, bajas y cambios de derechos solicitados y aprobados; revisión periódica.', tec: 'Flujo de solicitud en {ITSM} y revisión trimestral de accesos.', ev: 'Tickets de acceso; informes de revisión' },
  'op.acc.5': { org: 'Política de autenticación para usuarios externos (ciudadanía, proveedores).', tec: 'Autenticación con Cl@ve y certificado electrónico; doble factor para proveedores.', ev: 'Configuración de autenticación externa' },
  'op.acc.6': { org: 'Política de contraseñas y doble factor para el personal; custodia de credenciales.', tec: 'Doble factor en {IDP} para accesos remotos y administración.', ev: 'Política de contraseñas; configuración MFA' },
  'op.ext.1': { org: 'Contratos con cláusulas de seguridad, confidencialidad y ANS.', tec: 'Seguimiento de ANS en {ITSM}.', ev: 'Contratos; anexos de seguridad' },
  'op.ext.2': { org: 'Gestión diaria de proveedores: reuniones de seguimiento e informes de servicio.', tec: 'Cuadro de mando de ANS.', ev: 'Actas de seguimiento' },
  'op.ext.3': { org: 'Evaluación de seguridad de proveedores críticos y de su cadena de suministro.', tec: 'Cuestionario de seguridad y verificación de certificaciones.', ev: 'Evaluaciones de proveedores' },
  'op.ext.4': { org: 'Autorización y documentación de cada interconexión con terceros.', tec: 'Interconexiones inventariadas con cortafuegos y VPN dedicadas.', ev: 'Inventario de interconexiones' },
  'op.nub.1': { org: 'Servicios en la nube contratados a proveedores con certificación ENS del nivel requerido.', tec: 'Configuración segura de {CLOUD} según guía CCN-STIC de nube.', ev: 'Certificado ENS del proveedor; guía de configuración' },
  'op.exp.1': { org: 'Inventario de activos con responsable, ubicación y clasificación.', tec: 'CMDB en {ITSM} con descubrimiento automático.', ev: 'Inventario de activos' },
  'op.exp.2': { org: 'Configuración de seguridad de referencia para cada tipo de sistema.', tec: 'Plantillas bastionadas según guías CCN-STIC y comprobación periódica.', ev: 'Guías de bastionado; informes de cumplimiento' },
  'op.exp.3': { org: 'Gestión de la configuración de seguridad con control de versiones.', tec: 'Repositorio de configuraciones y detección de desviaciones.', ev: 'Líneas base de configuración' },
  'op.exp.4': { org: 'Procedimiento de parcheo con plazos por criticidad.', tec: 'Gestión de parches centralizada y escaneo de vulnerabilidades mensual.', ev: 'PRO-PAR-01; informes de parcheo' },
  'op.exp.5': { org: 'Gestión de cambios con evaluación de riesgo y marcha atrás.', tec: 'Flujo de cambios en {ITSM} con aprobación del CAB.', ev: 'Registro de cambios' },
  'op.exp.6': { org: 'Política de protección frente a código dañino en puestos y servidores.', tec: '{EDR} desplegado en puestos y servidores con consola central.', ev: 'Informe de cobertura del {EDR}' },
  'op.exp.7': { org: 'Procedimiento de gestión de incidentes y notificación al CCN-CERT.', tec: 'Registro y seguimiento de incidentes en {ITSM}.', ev: 'PRO-INC-01; registro de incidentes' },
  'op.exp.8': { org: 'Política de registro de actividad: qué se registra, retención y acceso.', tec: 'Centralización de registros en {SIEM}.', ev: 'Política de logs; configuración del {SIEM}' },
  'op.exp.9': { org: 'Registro de la gestión de incidentes con lecciones aprendidas.', tec: 'Informes de cierre en {ITSM}.', ev: 'Informes de incidentes' },
  'op.exp.10': { org: 'Ciclo de vida de claves criptográficas: generación, custodia, rotación y destrucción.', tec: 'Custodia de claves en almacén seguro con acceso restringido.', ev: 'PRO-CRI-01; inventario de claves' },
  'op.cont.1': { org: 'Análisis de impacto en el negocio con RTO y RPO por servicio.', tec: 'Mapa de dependencias desde la CMDB.', ev: 'BIA vigente' },
  'op.cont.2': { org: 'Plan de continuidad aprobado con roles y escenarios.', tec: 'Procedimientos de recuperación documentados.', ev: 'Plan de continuidad' },
  'op.cont.3': { org: 'Pruebas periódicas del plan de continuidad.', tec: 'Simulacros de recuperación con informe de resultados.', ev: 'Informes de pruebas' },
  'op.cont.4': { org: 'Medios alternativos para servicios críticos.', tec: 'Réplica en {CPD} secundario o en {CLOUD}.', ev: 'Diseño de medios alternativos' },
  'op.mon.1': { org: 'Detección de intrusiones en el perímetro y en segmentos críticos.', tec: 'IDS/IPS con reglas actualizadas y alertas al equipo de seguridad.', ev: 'Configuración del IDS/IPS' },
  'op.mon.2': { org: 'Sistema de métricas de seguridad con indicadores y umbrales.', tec: 'Cuadro de mando mensual de indicadores.', ev: 'Cuadro de mando de seguridad' },
  'op.mon.3': { org: 'Vigilancia continua: correlación de eventos y respuesta.', tec: 'Casos de uso de correlación en {SIEM}.', ev: 'Catálogo de casos de uso' },
  'mp.if.1': { org: 'Áreas de seguridad identificadas con acceso restringido.', tec: 'Control de acceso físico por tarjeta a salas técnicas.', ev: 'Plano de áreas; registros de acceso' },
  'mp.if.2': { org: 'Identificación de todas las personas que acceden a áreas restringidas.', tec: 'Registro de visitas y acreditaciones.', ev: 'Libro de visitas' },
  'mp.if.3': { org: 'Acondicionamiento de locales: temperatura, humedad y cableado.', tec: 'Climatización redundante con sondas.', ev: 'Informe de mantenimiento' },
  'mp.if.4': { org: 'Suministro eléctrico garantizado para equipos críticos.', tec: 'SAI y grupo electrógeno con pruebas periódicas.', ev: 'Pruebas de SAI' },
  'mp.if.5': { org: 'Protección frente a incendios conforme a normativa.', tec: 'Detección y extinción automática en sala técnica.', ev: 'Certificado de mantenimiento PCI' },
  'mp.if.6': { org: 'Protección frente a inundaciones.', tec: 'Sensores de agua y suelo técnico elevado.', ev: 'Informe de instalaciones' },
  'mp.if.7': { org: 'Registro de entrada y salida de equipamiento.', tec: 'Registro en {ITSM} vinculado al inventario.', ev: 'Registro de movimientos' },
  'mp.per.1': { org: 'Caracterización de puestos con requisitos de seguridad.', tec: 'Perfiles de puesto con nivel de acceso.', ev: 'Fichas de puesto' },
  'mp.per.2': { org: 'Deberes y obligaciones de seguridad comunicados y firmados.', tec: 'Firma electrónica del compromiso de confidencialidad.', ev: 'Compromisos firmados' },
  'mp.per.3': { org: 'Plan anual de concienciación para todo el personal.', tec: 'Plataforma de formación en línea y campañas de phishing simulado.', ev: 'Plan de concienciación; resultados de campañas' },
  'mp.per.4': { org: 'Formación específica para personal técnico y de seguridad.', tec: 'Itinerarios formativos por perfil.', ev: 'Registro de formación' },
  'mp.eq.1': { org: 'Norma de puesto de trabajo despejado.', tec: 'Bloqueo de pantalla y armarios con llave.', ev: 'NOR de puesto de trabajo' },
  'mp.eq.2': { org: 'Bloqueo automático del puesto por inactividad.', tec: 'Directiva de bloqueo a los 10 minutos.', ev: 'Directiva de grupo' },
  'mp.eq.3': { org: 'Protección de portátiles y móviles corporativos.', tec: 'Cifrado de disco y gestión de dispositivos móviles.', ev: 'Consola MDM; informe de cifrado' },
  'mp.eq.4': { org: 'Control de otros dispositivos conectados a la red (impresoras, IoT).', tec: 'Inventario y segmentación de dispositivos.', ev: 'Inventario de dispositivos' },
  'mp.com.1': { org: 'Perímetro seguro con política de filtrado documentada.', tec: 'Cortafuegos perimetrales con revisión de reglas.', ev: 'Política de filtrado; revisión de reglas' },
  'mp.com.2': { org: 'Protección de la confidencialidad en las comunicaciones.', tec: 'TLS 1.2+ y VPN cifradas según CCN-STIC 807.', ev: 'Configuración criptográfica' },
  'mp.com.3': { org: 'Protección de la integridad y autenticidad de las comunicaciones.', tec: 'Autenticación mutua y firma de mensajes en interconexiones.', ev: 'Configuración de túneles' },
  'mp.com.4': { org: 'Separación de flujos de información en la red.', tec: 'Segmentación por VLAN y zonas de seguridad.', ev: 'Diagrama de segmentación' },
  'mp.si.1': { org: 'Marcado de soportes según clasificación.', tec: 'Etiquetado de soportes extraíbles.', ev: 'NOR de soportes' },
  'mp.si.2': { org: 'Cifrado de la información en soportes.', tec: 'Cifrado de discos y copias.', ev: 'Configuración de cifrado' },
  'mp.si.3': { org: 'Custodia de soportes en lugar seguro.', tec: 'Armario ignífugo y registro de soportes.', ev: 'Registro de custodia' },
  'mp.si.4': { org: 'Transporte seguro de soportes.', tec: 'Transporte con registro y cifrado.', ev: 'Registro de transporte' },
  'mp.si.5': { org: 'Borrado seguro y destrucción de soportes.', tec: 'Borrado certificado y destrucción física por proveedor homologado.', ev: 'Certificados de destrucción' },
  'mp.sw.1': { org: 'Desarrollo seguro: requisitos, revisión de código y pruebas.', tec: 'Análisis estático en el ciclo de integración continua.', ev: 'Guía de desarrollo seguro; informes SAST' },
  'mp.sw.2': { org: 'Aceptación y puesta en servicio con pruebas de seguridad.', tec: 'Pruebas de seguridad previas a producción.', ev: 'Actas de aceptación' },
  'mp.info.1': { org: 'Tratamientos de datos personales conforme al RGPD y LOPDGDD.', tec: 'Registro de actividades de tratamiento y evaluaciones de impacto.', ev: 'RAT; EIPD' },
  'mp.info.2': { org: 'Calificación de la información por su responsable.', tec: 'Etiquetado en el gestor documental.', ev: 'Esquema de clasificación' },
  'mp.info.3': { org: 'Firma electrónica en documentos y actuaciones.', tec: 'Plataforma de firma con certificados cualificados.', ev: 'Configuración de firma' },
  'mp.info.4': { org: 'Sellos de tiempo en documentos que lo requieren.', tec: 'Servicio de sellado de tiempo cualificado.', ev: 'Configuración de sellado' },
  'mp.info.5': { org: 'Limpieza de metadatos antes de publicar documentos.', tec: 'Herramienta de limpieza en el flujo de publicación.', ev: 'Procedimiento de publicación' },
  'mp.info.6': { org: 'Política de copias de seguridad con retención y pruebas de restauración.', tec: 'Copias con {BACKUP} y copia externa inmutable.', ev: 'Política de copias; pruebas de restauración' },
  'mp.s.1': { org: 'Protección del correo electrónico.', tec: 'Filtrado antispam, antimalware y SPF/DKIM/DMARC en {MAIL}.', ev: 'Configuración del correo' },
  'mp.s.2': { org: 'Protección de servicios y aplicaciones web.', tec: '{WAF} delante de los servicios web y pruebas de seguridad periódicas.', ev: 'Configuración del WAF; informes de pruebas' },
  'mp.s.3': { org: 'Protección de la navegación web.', tec: 'Filtrado de navegación por categorías y reputación.', ev: 'Política de navegación' },
  'mp.s.4': { org: 'Protección frente a denegación de servicio.', tec: 'Mitigación DDoS del proveedor de comunicaciones.', ev: 'Contrato de mitigación DDoS' }
};
